import 'package:eks_sana_plus_org/src/common/constants/service_type.dart';
import 'package:eks_sana_plus_org/src/features/services/data/models/home_service_request_model.dart';

import 'abstract/base_request_entity.dart';

class HomeServiceRequestEntity extends BaseRequestEntity {
  final String? requestDay;
  final String? bookedDateTimeJalali;

  final String? emdadServiceCategoryTitle;
  final String? emdadgarName;

  final String? agencyName;
  final String? agencyCode;

  final String? requestDateTime;
  final String? requestDayTime;
  final bool? vip;
  final String? vipConditionTitle;
  final String? emdadProductTitle;

  const HomeServiceRequestEntity({
    super.id,
    super.trackCode,
    super.firstName,
    super.lastName,
    super.latitude,
    super.longitude,
    super.aidAddress,
    super.cityName,
    super.provinceName,
    super.carName,
    super.carProductionYear,
    super.licensePlate,
    super.requestStatus,
    super.requestStatusTitle,
    super.requestDateJalali,
    super.requestTime,
    super.customerMobileNumber,
    super.description,
    super.carColorTitle,
    super.carEngineNumber,
    super.genderTitle,
    super.personTypeTitle,
    super.chassisNumber,
    super.kilometer,
    super.nationalNumber,
    super.dispatcher,
    super.emFullName,
    super.emMobileNumber1,
    super.emVehicleTypeTitle,
    super.emVehicleType,
    super.emVehicleSubTypeTitle,
    super.emVehicleSubType,
    super.emRepresentationName,
    super.emRepresentationCode,
    super.isGuaranty,
    super.isSubscription,
    this.requestDay,
    this.bookedDateTimeJalali,
    this.emdadServiceCategoryTitle,
    this.emdadgarName,
    this.agencyName,
    this.agencyCode,
    this.requestDateTime,
    this.requestDayTime,
    this.vip,
    this.vipConditionTitle,
    this.emdadProductTitle,
    super.serviceType,
    super.agencyVehicleLabelCode,
    super.assignDate,
    super.assignDateTimeJalali,
    super.callMobileNumber,
    super.carFactory,
    super.carFactoryTitle,
    super.carGroupTitle,
    super.carInfoGuid,
    super.carInfoId,
    super.carModelId,
    super.emdadgarId,
    super.garantyCarTipId,
    super.garantyDescription,
    super.garantyEndDate,
    super.garantyIsGaranty,
    super.garantyLastKilometer,
    super.garantyReceptionDate,
    super.garantySiteDescription,
    super.garantyStartDate,
    super.garantyStatusCode,
    super.hasEmdadgar,
    super.insertDateTime,
    super.insertDateTimeJalali,
    super.invoiceDocumentGuid,
    super.isSaipa,
    super.personType,
    super.planningId,
    super.requestDateTimeJalali,
    super.vehicleUsageId,
    super.vehicleUsageTitle,
    super.wageGroupType,
    super.weightGroupTitle,
  });

  HomeServiceRequestModel toModel() {
    return HomeServiceRequestModel(
      id: id,
      trackCode: trackCode,
      firstName: firstName,
      lastName: lastName,
      latitude: latitude,
      longitude: longitude,
      aidAddress: aidAddress,
      cityName: cityName,
      provinceName: provinceName,
      carName: carName,
      carProductionYear: carProductionYear,
      licensePlate: licensePlate,
      requestStatus: requestStatus,
      requestStatusTitle: requestStatusTitle,
      requestDateJalali: requestDateJalali,
      requestTime: requestTime,
      requestDay: requestDay,
      bookedDateTimeJalali: bookedDateTimeJalali,
      emdadServiceCategoryTitle: emdadServiceCategoryTitle,
      emdadgarName: emdadgarName,
      agencyName: agencyName,
      agencyCode: agencyCode,
      customerMobileNumber: customerMobileNumber,
      description: description,
      carColorTitle: carColorTitle,
      carEngineNumber: carEngineNumber,
      genderTitle: genderTitle,
      personTypeTitle: personTypeTitle,
      chassisNumber: chassisNumber,
      kilometer: kilometer,
      nationalNumber: nationalNumber,
      dispatcher: dispatcher,
      emFullName: emFullName,
      emMobileNumber1: emMobileNumber1,
      emVehicleTypeTitle: emVehicleTypeTitle,
      emVehicleType: emVehicleType,
      emVehicleSubTypeTitle: emVehicleSubTypeTitle,
      emVehicleSubType: emVehicleSubType,
      emRepresentationName: emRepresentationName,
      emRepresentationCode: emRepresentationCode,
      isGuaranty: isGuaranty,
      isSubscription: isSubscription,
      requestDateTime: requestDateTime,
      requestDayTime: requestDayTime,
      vip: vip,
      vipConditionTitle: vipConditionTitle,
      emdadProductTitle: emdadProductTitle,
      serviceType: serviceType,
    );
  }
}
