import 'package:eks_sana_plus_org/src/features/services/data/models/home_service_request_model.dart';

import 'abstract/base_request_entity.dart';

class HomeServiceRequestEntity extends BaseRequestEntity {
  final String? requestDay;
  final String? bookedDateTimeJalali;

  final String? emdadServiceCategoryTitle;
  final String? emdadgarName;

  final String? agencyName;
  final String? agencyCode;

  final String? requestDateTime;
  final String? requestDayTime;
  final bool? vip;
  final String? vipConditionTitle;
  final String? emdadProductTitle;

  const HomeServiceRequestEntity({
    super.trackCode,
    super.firstName,
    super.lastName,
    super.latitude,
    super.longitude,
    super.aidAddress,
    super.cityName,
    super.provinceName,
    super.carName,
    super.carProductionYear,
    super.licensePlate,
    super.requestStatus,
    super.requestStatusTitle,
    super.requestDateJalali,
    super.requestTime,
    super.customerMobileNumber,
    super.description,
    super.carColorTitle,
    super.carEngineNumber,
    super.genderTitle,
    super.personTypeTitle,
    super.chassisNumber,
    super.kilometer,
    super.nationalNumber,
    super.dispatcher,
    super.emFullName,
    super.emMobileNumber1,
    super.emVehicleTypeTitle,
    super.emVehicleType,
    super.emVehicleSubTypeTitle,
    super.emVehicleSubType,
    super.emRepresentationName,
    super.emRepresentationCode,
    super.isGuaranty,
    super.isSubscription,
    this.requestDay,
    this.bookedDateTimeJalali,
    this.emdadServiceCategoryTitle,
    this.emdadgarName,
    this.agencyName,
    this.agencyCode,
    this.requestDateTime,
    this.requestDayTime,
    this.vip,
    this.vipConditionTitle,
    this.emdadProductTitle,
  });

  HomeServiceRequestEntity copyWith({
    int? trackCode,
    String? firstName,
    String? lastName,
    String? chassisNumber,
    int? kilometer,
    String? nationalNumber,
    double? latitude,
    double? longitude,
    String? aidAddress,
    String? cityName,
    String? provinceName,
    String? carName,
    int? carProductionYear,
    String? licensePlate,
    int? requestStatus,
    String? requestStatusTitle,
    String? requestDateJalali,
    String? requestTime,
    String? customerMobileNumber,
    String? description,
    String? carColorTitle,
    String? carEngineNumber,
    String? genderTitle,
    String? personTypeTitle,
    String? dispatcher,
    bool? isGuaranty,
    bool? isSubscription,
    String? emFullName,
    String? emMobileNumber1,
    String? emVehicleTypeTitle,
    int? emVehicleType,
    String? emVehicleSubTypeTitle,
    int? emVehicleSubType,
    String? emRepresentationName,
    String? emRepresentationCode,
    String? requestDay,
    String? bookedDateTimeJalali,
    String? emdadServiceCategoryTitle,
    String? emdadgarName,
    String? agencyName,
    String? agencyCode,
    String? requestDateTime,
    String? requestDayTime,
    bool? vip,
    String? vipConditionTitle,
    String? emdadProductTitle,
  }) {
    return HomeServiceRequestEntity(
      trackCode: trackCode ?? this.trackCode,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      aidAddress: aidAddress ?? this.aidAddress,
      cityName: cityName ?? this.cityName,
      provinceName: provinceName ?? this.provinceName,
      carName: carName ?? this.carName,
      carProductionYear: carProductionYear ?? this.carProductionYear,
      licensePlate: licensePlate ?? this.licensePlate,
      requestStatus: requestStatus ?? this.requestStatus,
      requestStatusTitle: requestStatusTitle ?? this.requestStatusTitle,
      requestDateJalali: requestDateJalali ?? this.requestDateJalali,
      requestTime: requestTime ?? this.requestTime,
      chassisNumber: chassisNumber ?? this.chassisNumber,
      kilometer: kilometer ?? this.kilometer,
      nationalNumber: nationalNumber ?? this.nationalNumber,
      customerMobileNumber: customerMobileNumber ?? this.customerMobileNumber,
      description: description ?? this.description,
      carColorTitle: carColorTitle ?? this.carColorTitle,
      carEngineNumber: carEngineNumber ?? this.carEngineNumber,
      genderTitle: genderTitle ?? this.genderTitle,
      personTypeTitle: personTypeTitle ?? this.personTypeTitle,
      dispatcher: dispatcher ?? this.dispatcher,
      isGuaranty: isGuaranty ?? this.isGuaranty,
      isSubscription: isSubscription ?? this.isSubscription,
      emFullName: emFullName ?? this.emFullName,
      emMobileNumber1: emMobileNumber1 ?? this.emMobileNumber1,
      emVehicleTypeTitle: emVehicleTypeTitle ?? this.emVehicleTypeTitle,
      emVehicleType: emVehicleType ?? this.emVehicleType,
      emVehicleSubTypeTitle:
          emVehicleSubTypeTitle ?? this.emVehicleSubTypeTitle,
      emVehicleSubType: emVehicleSubType ?? this.emVehicleSubType,
      emRepresentationName: emRepresentationName ?? this.emRepresentationName,
      emRepresentationCode: emRepresentationCode ?? this.emRepresentationCode,
      requestDay: requestDay ?? this.requestDay,
      bookedDateTimeJalali: bookedDateTimeJalali ?? this.bookedDateTimeJalali,
      emdadServiceCategoryTitle:
          emdadServiceCategoryTitle ?? this.emdadServiceCategoryTitle,
      emdadgarName: emdadgarName ?? this.emdadgarName,
      agencyName: agencyName ?? this.agencyName,
      agencyCode: agencyCode ?? this.agencyCode,
      requestDateTime: requestDateTime ?? this.requestDateTime,
      requestDayTime: requestDayTime ?? this.requestDayTime,
      vip: vip ?? this.vip,
      vipConditionTitle: vipConditionTitle ?? this.vipConditionTitle,
      emdadProductTitle: emdadProductTitle ?? this.emdadProductTitle,
    );
  }

  HomeServiceRequestModel toModel() {
    return HomeServiceRequestModel(
      trackCode: trackCode,
      firstName: firstName,
      lastName: lastName,
      latitude: latitude,
      longitude: longitude,
      aidAddress: aidAddress,
      cityName: cityName,
      provinceName: provinceName,
      carName: carName,
      carProductionYear: carProductionYear,
      licensePlate: licensePlate,
      requestStatus: requestStatus,
      requestStatusTitle: requestStatusTitle,
      requestDateJalali: requestDateJalali,
      requestTime: requestTime,
      requestDay: requestDay,
      bookedDateTimeJalali: bookedDateTimeJalali,
      emdadServiceCategoryTitle: emdadServiceCategoryTitle,
      emdadgarName: emdadgarName,
      agencyName: agencyName,
      agencyCode: agencyCode,
    );
  }
}
