import 'package:eks_sana_plus_org/src/features/services/data/models/relief_request_model.dart';

import 'abstract/base_request_entity.dart';

class ReliefRequestEntity extends BaseRequestEntity {
  final int? defectId;
  final String? defectTitle;

  final bool? isUrgentRequest;

  final String? emdadServiceTitle;

  final String? hamlReasonTitle;
  final String? wheelQuestionTitle;

  final String? emdadgarAssignDistanceTitle;
  final String? emdadgarAssignDurationTitle;

  final String? assignDate;
  final String? assignTime;

  const ReliefRequestEntity({
    super.trackCode,
    super.firstName,
    super.lastName,
    super.latitude,
    super.longitude,
    super.aidAddress,
    super.cityName,
    super.provinceName,
    super.carName,
    super.carProductionYear,
    super.licensePlate,
    super.requestStatus,
    super.requestStatusTitle,
    super.requestDateJalali,
    super.requestTime,
    super.customerMobileNumber,
    super.description,
    super.carColorTitle,
    super.carEngineNumber,
    super.genderTitle,
    super.personTypeTitle,
    super.chassisNumber,
    super.kilometer,
    super.nationalNumber,
    super.emFullName,
    super.emMobileNumber1,
    super.emVehicleTypeTitle,
    super.emVehicleType,
    super.emVehicleSubTypeTitle,
    super.emVehicleSubType,
    super.emRepresentationName,
    super.emRepresentationCode,
    super.isGuaranty,
    super.isSubscription,
    super.dispatcher,
    this.defectId,
    this.defectTitle,
    this.isUrgentRequest,
    this.emdadServiceTitle,
    this.hamlReasonTitle,
    this.wheelQuestionTitle,
    this.emdadgarAssignDistanceTitle,
    this.emdadgarAssignDurationTitle,
    this.assignDate,
    this.assignTime,
  });

  ReliefRequestEntity copyWith({
    int? trackCode,
    String? firstName,
    String? lastName,
    String? chassisNumber,
    int? kilometer,
    String? nationalNumber,
    double? latitude,
    double? longitude,
    String? aidAddress,
    String? cityName,
    String? provinceName,
    String? carName,
    int? carProductionYear,
    String? licensePlate,
    int? requestStatus,
    String? requestStatusTitle,
    String? requestDateJalali,
    String? requestTime,
    String? customerMobileNumber,
    String? description,
    String? carColorTitle,
    String? carEngineNumber,
    String? genderTitle,
    String? personTypeTitle,
    String? dispatcher,
    bool? isGuaranty,
    bool? isSubscription,
    String? emFullName,
    String? emMobileNumber1,
    String? emVehicleTypeTitle,
    int? emVehicleType,
    String? emVehicleSubTypeTitle,
    int? emVehicleSubType,
    String? emRepresentationName,
    String? emRepresentationCode,
    int? defectId,
    String? defectTitle,
    bool? isUrgentRequest,
    String? emdadServiceTitle,
    String? hamlReasonTitle,
    String? wheelQuestionTitle,
    String? emdadgarAssignDistanceTitle,
    String? emdadgarAssignDurationTitle,
    String? assignDate,
    String? assignTime,
  }) {
    return ReliefRequestEntity(
      trackCode: trackCode ?? this.trackCode,
      firstName: firstName ?? this.firstName,
      lastName: lastName ?? this.lastName,
      latitude: latitude ?? this.latitude,
      longitude: longitude ?? this.longitude,
      aidAddress: aidAddress ?? this.aidAddress,
      cityName: cityName ?? this.cityName,
      provinceName: provinceName ?? this.provinceName,
      carName: carName ?? this.carName,
      carProductionYear: carProductionYear ?? this.carProductionYear,
      licensePlate: licensePlate ?? this.licensePlate,
      requestStatus: requestStatus ?? this.requestStatus,
      requestStatusTitle: requestStatusTitle ?? this.requestStatusTitle,
      requestDateJalali: requestDateJalali ?? this.requestDateJalali,
      requestTime: requestTime ?? this.requestTime,
      chassisNumber: chassisNumber ?? this.chassisNumber,
      kilometer: kilometer ?? this.kilometer,
      nationalNumber: nationalNumber ?? this.nationalNumber,
      customerMobileNumber: customerMobileNumber ?? this.customerMobileNumber,
      description: description ?? this.description,
      carColorTitle: carColorTitle ?? this.carColorTitle,
      carEngineNumber: carEngineNumber ?? this.carEngineNumber,
      genderTitle: genderTitle ?? this.genderTitle,
      personTypeTitle: personTypeTitle ?? this.personTypeTitle,
      dispatcher: dispatcher ?? this.dispatcher,
      isGuaranty: isGuaranty ?? this.isGuaranty,
      isSubscription: isSubscription ?? this.isSubscription,
      emFullName: emFullName ?? this.emFullName,
      emMobileNumber1: emMobileNumber1 ?? this.emMobileNumber1,
      emVehicleTypeTitle: emVehicleTypeTitle ?? this.emVehicleTypeTitle,
      emVehicleType: emVehicleType ?? this.emVehicleType,
      emVehicleSubTypeTitle:
          emVehicleSubTypeTitle ?? this.emVehicleSubTypeTitle,
      emVehicleSubType: emVehicleSubType ?? this.emVehicleSubType,
      emRepresentationName: emRepresentationName ?? this.emRepresentationName,
      emRepresentationCode: emRepresentationCode ?? this.emRepresentationCode,
      defectId: defectId ?? this.defectId,
      defectTitle: defectTitle ?? this.defectTitle,
      isUrgentRequest: isUrgentRequest ?? this.isUrgentRequest,
      emdadServiceTitle: emdadServiceTitle ?? this.emdadServiceTitle,
      hamlReasonTitle: hamlReasonTitle ?? this.hamlReasonTitle,
      wheelQuestionTitle: wheelQuestionTitle ?? this.wheelQuestionTitle,
      emdadgarAssignDistanceTitle:
          emdadgarAssignDistanceTitle ?? this.emdadgarAssignDistanceTitle,
      emdadgarAssignDurationTitle:
          emdadgarAssignDurationTitle ?? this.emdadgarAssignDurationTitle,
      assignDate: assignDate ?? this.assignDate,
      assignTime: assignTime ?? this.assignTime,
    );
  }

  ReliefRequestModel toModel() {
    return ReliefRequestModel(
      trackCode: trackCode,
      firstName: firstName,
      lastName: lastName,
      latitude: latitude,
      longitude: longitude,
      aidAddress: aidAddress,
      cityName: cityName,
      provinceName: provinceName,
      carName: carName,
      carProductionYear: carProductionYear,
      licensePlate: licensePlate,
      requestStatus: requestStatus,
      requestStatusTitle: requestStatusTitle,
      requestDateJalali: requestDateJalali,
      requestTime: requestTime,
      defectId: defectId,
      defectTitle: defectTitle,
      isUrgentRequest: isUrgentRequest,
      emdadServiceTitle: emdadServiceTitle,
      customerMobileNumber: customerMobileNumber,
      description: description,
      carColorTitle: carColorTitle,
      carEngineNumber: carEngineNumber,
      genderTitle: genderTitle,
      personTypeTitle: personTypeTitle,
    );
  }
}
