class RequestOperationAccessEntity {
  const RequestOperationAccessEntity({
    this.cancel = false,
    this.cancelAfterAssign = false,
    this.cancelBeforeAssign = false,
    this.assign = false,
    this.assignCancel = false,
    this.lackOfCooperation = false,
    this.cartableCycle = false,
    this.followUp = false,
    this.invoiceCancel = false,
    this.customerInvoice = false,
    this.emdadgarInvoice = false,
    this.invoiceRegistration = false,
    this.externalEmdadNavgan = false,
    this.cancelExternalEmdadNavgan = false,
    this.serviceRequestCopy = false,
    this.evaluationHistory = false,
    this.invoiceModification = false,
    this.urgentServiceRequestCompleted = false,
    this.smsHistory = false,
    this.viewAssignHistory = false,
    this.canInsert = false,
    this.canView = false,
    this.canUpdate = false,
    this.canDelete = false,
    this.canExport = false,
    this.canPrint = false,
    this.canImport = false,
    this.canViewUserRole = false,
    this.canViewUserOperation = false,
    this.changeUserPassword = false,
  });

  final bool cancel;
  final bool cancelAfterAssign;
  final bool cancelBeforeAssign;
  final bool assign;
  final bool assignCancel;
  final bool lackOfCooperation;
  final bool cartableCycle;
  final bool followUp;
  final bool invoiceCancel;
  final bool customerInvoice;
  final bool emdadgarInvoice;
  final bool invoiceRegistration;
  final bool externalEmdadNavgan;
  final bool cancelExternalEmdadNavgan;
  final bool serviceRequestCopy;
  final bool evaluationHistory;
  final bool invoiceModification;
  final bool urgentServiceRequestCompleted;
  final bool smsHistory;
  final bool viewAssignHistory;
  final bool canInsert;
  final bool canView;
  final bool canUpdate;
  final bool canDelete;
  final bool canExport;
  final bool canPrint;
  final bool canImport;
  final bool canViewUserRole;
  final bool canViewUserOperation;
  final bool changeUserPassword;
}
